#!/usr/bin/env bash

## Leave them empty, set them in file 'cluster.conf'
PROJECT=""
ZONE=""
NODES=""
SSH_PUB_KEY=""
MACHINE_TYPE=""

source cluster.conf

## Two color codes.
SY=$'\x1b[33;1m'
NC=$'\x1b[0m'

for ((i=1; i<=$NODES; i++)); do
    n="$(printf "%02d" $i)"
    gcloud compute ssh node-$n \
	--zone ${ZONE} \
	--project ${PROJECT} \
	--command "$1"
done

